name: Deploy Next.js to AlmaLinux

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r .next next.config.js* package.json package-lock.json public deployment/
        tar -czf deployment.tar.gz deployment/

    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "SSH connection test successful"
          date

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.4  # Use latest version
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "deployment.tar.gz"
        target: "/tmp/"
        debug: true  # Enable debug mode

    - name: Extract and restart on server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /var/www/dashboard
          
          # Backup current deployment
          tar -czf backup_$(date +%Y%m%d_%H%M%S).tar.gz ./* 2>/dev/null || true
          
          # Extract new deployment
          tar -xzf /tmp/deployment.tar.gz -C /tmp/
          cp -r /tmp/deployment/* .
          rm -rf /tmp/deployment /tmp/deployment.tar.gz
          
          # Install production dependencies only
          npm ci --only=production
          
          # Restart application
          pm2 restart all || pm2 start npm --name "app" -- start
          
          # Cleanup old backups
          ls -t backup_*.tar.gz 2>/dev/null | tail -n +6 | xargs rm -f
